### ISSUE TITLE
Question regarding models

### ISSUE THREAD

**Issue by smiLLe** [Jairzinno/hue_dart#1]
Hi @Jairzinno 
this is a great library :)! I recently started to use dart and flutter. I want to build a small privat hue app and found your library.
So my question is about the models and json_serzializer. I am using built_value for another project which automatically genreates the == operator and .hashCode. Something that is completey missing in json_serializer. Also you are mutating your model objects ... lights.on = true ...  The flutter devs often use a .copyWith function to create a new (in this case light) model/object , something that built_value also does (a bit different but it still creates a new object).

So before i am going to fork or recreate a whole new hue_dart library i wanted to ask you, if you are open for this kind of changes?
Not necessarily using built_value (which is great btw :) ) over json_serializer but making model properties final and expose ==, .hashCode and copyWith? If so i will do a pull request with first changes.

You might asking why == or .hashCode is important?
Let's assume i am polling the hue bridge every second for all lights and i am exposing the List<Light> through a Stream.
I have a StreamBuilder WIdget in flutter which updates it's children whenever it receives a new event by the stream. This would recreate every single child even if they were still the same. this is where == operator really shines.

**Comment by Jairzinno** [comment]
Hi @Michael,
Thanks for the suggestion. Sounds like a great idea! Please go ahead. Let me know if I can help in any kind of way

**Comment by Jairzinno** [comment]
I'm not familiar with it (as in haven't used it before) but having read on it I think it's the best way forward and you're suggestion really makes sense. Better to have something write it for you than do it yourself ;).

**Comment by smiLLe** [comment]
Okay :) I will have a look into migrating to built_value in the fork i created, this weekend
