### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by drachim-dev** [Jairzinno/hue_dart#7]
Please update the package to support null safety:
[https://dart.dev/null-safety](https://dart.dev/null-safety)

**Comment by guyluz11** [comment]
It looks like your wish came true @drachim-dev 

![image](https://user-images.githubusercontent.com/9304740/131229752-d79c63c7-91e8-4f87-886e-4ae8f2034317.png)

**Comment by drachim-dev** [comment]
Oh yes, you are right!
Will close this issue :)
